# Generated by Django 3.0.6 on 2020-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0004_auto_20200513_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zdjecie_profilowe',
            field=models.ImageField(default='user.png', null=True, upload_to=''),
        ),
    ]
