# Generated by Django 3.0.6 on 2020-05-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0005_auto_20200513_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obserwowani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obserwowany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obserwowany', to='PhotoHubAPP.UserProfile')),
                ('obserwujacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.UserProfile')),
            ],
        ),
    ]
