# Generated by Django 3.0.6 on 2020-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0007_auto_20200514_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowani',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
