# Generated by Django 3.0.6 on 2020-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0008_obserwowani_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowani',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
