# Generated by Django 3.0.6 on 2020-05-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0009_obserwowani_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obserwowani',
            name='obserwowany',
        ),
    ]
