# Generated by Django 3.0.6 on 2020-05-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0010_remove_obserwowani_obserwowany'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowani',
            name='obserwowany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obserwowany_set', to='PhotoHubAPP.UserProfile'),
        ),
    ]
