# Generated by Django 3.0.6 on 2020-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0011_obserwowani_obserwowany'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
