# Generated by Django 3.0.6 on 2020-05-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0012_userprofile_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='check',
        ),
    ]
