# Generated by Django 3.0.6 on 2020-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0014_auto_20200514_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plec',
            field=models.CharField(blank=True, choices=[('', 'Podaj swoja plec'), ('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1, null=True),
        ),
    ]
