# Generated by Django 3.0.6 on 2020-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0015_userprofile_plec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obserwowani',
            name='check',
        ),
        migrations.RemoveField(
            model_name='obserwowani',
            name='info',
        ),
        migrations.AddField(
            model_name='obserwowani',
            name='data_stworzenia',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
