# Generated by Django 3.0.6 on 2020-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0016_auto_20200515_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowani',
            name='imie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obserwowani',
            name='nazwisko',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
