# Generated by Django 3.0.6 on 2020-05-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0017_auto_20200515_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PhotoHubAPP.UserProfile'),
        ),
    ]
