# Generated by Django 3.0.6 on 2020-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0021_auto_20200522_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='if_like',
            field=models.BooleanField(default=False, help_text='Jesli zalajkujesz post, zmieni sie na True'),
        ),
    ]
