# Generated by Django 3.0.6 on 2020-08-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0022_post_if_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='if_like',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.UserProfile'),
        ),
    ]
