# Generated by Django 3.0.6 on 2020-08-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0024_auto_20200811_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('tresc', models.CharField(max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.Post')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.UserProfile')),
            ],
        ),
    ]
