# Generated by Django 3.0.6 on 2020-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0025_komentarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='tresc',
            field=models.TextField(max_length=500),
        ),
    ]
