# Generated by Django 3.0.6 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0027_post_komentarze_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ukryty',
            field=models.BooleanField(default=False),
        ),
    ]
