# Generated by Django 3.0.6 on 2020-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0028_userprofile_ukryty'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowani',
            name='prosba',
            field=models.BooleanField(default=False, help_text='Dotyczy tylko obserwowania profili ukrytych'),
        ),
        migrations.AddField(
            model_name='obserwowani',
            name='zgoda',
            field=models.BooleanField(default=False, help_text='Dotyczy tylko obserwowania profili ukrytych'),
        ),
    ]
