# Generated by Django 3.0.6 on 2020-08-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0030_obserwowanipowiadomienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowanipowiadomienia',
            name='obserwujacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.UserProfile'),
        ),
    ]
