# Generated by Django 3.0.6 on 2020-08-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0031_obserwowanipowiadomienia_obserwujacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='obserwowanipowiadomienia',
            name='obserwowany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obserwowany_sett', to='PhotoHubAPP.UserProfile'),
        ),
    ]
