# Generated by Django 3.0.6 on 2020-08-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0033_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='follow',
            field=models.IntegerField(default=0, help_text='0 - brak działania, 1 - usunięcie, 2 dodanie'),
        ),
        migrations.AddField(
            model_name='historia',
            name='follow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoHubAPP.Obserwowani'),
        ),
    ]
