# Generated by Django 3.0.6 on 2020-08-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0034_auto_20200814_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='czas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='follow',
            field=models.IntegerField(default=0, help_text='0 - brak działania, 1 - usunięcie, 2 dodanie, 5 - wyświetlone'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='komentarz',
            field=models.IntegerField(default=0, help_text='0 - brak działania, 1 - usunięcie, 2 dodanie, 5 - wyświetlone'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='like',
            field=models.IntegerField(default=0, help_text='0 - brak działania, 1 - usunięcie, 2 dodanie, 5 - wyświetlone'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='post',
            field=models.IntegerField(default=0, help_text='0 - brak działania, 1 - usunięcie, 2 dodanie, 5 - wyświetlone'),
        ),
    ]
