# Generated by Django 3.0.6 on 2020-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0035_auto_20200817_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='usuniete_zdarzenie',
            field=models.ManyToManyField(blank=True, null=True, to='PhotoHubAPP.UserProfile'),
        ),
    ]
