# Generated by Django 3.0.6 on 2020-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0036_historia_usuniete_zdarzenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='usuniete_zdarzenie',
            field=models.ManyToManyField(blank=True, help_text='Jesli na tej liscie znajduje sie uzytkownik to znaczy ze wyswietlil dane zdarzenie', null=True, to='PhotoHubAPP.UserProfile'),
        ),
    ]
