# Generated by Django 3.0.6 on 2020-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0037_auto_20200914_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='PhotoHubAPP.UserProfile'),
        ),
    ]
