# Generated by Django 3.0.6 on 2020-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0038_auto_20200915_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='tytul',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
