# Generated by Django 3.0.6 on 2020-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0039_historia_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='tresc',
            field=models.CharField(max_length=500),
        ),
    ]
