# Generated by Django 3.0.6 on 2020-09-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoHubAPP', '0040_auto_20200916_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='PhotoHubAPP.Post'),
        ),
    ]
